# Generated by Django 2.0.6 on 2018-10-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='enterprise',
            field=models.ManyToManyField(to='misclientes.Enterprise'),
        ),
    ]
