# Generated by Django 3.0.8 on 2020-08-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_of_Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='type_of_contract',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='type_of_contract',
            field=models.ManyToManyField(max_length=20, null=True, to='misclientes.Type_of_Contract'),
        ),
    ]
