# Generated by Django 2.0.6 on 2018-10-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0002_auto_20181010_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='idnum',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='has_doubt',
            field=models.BooleanField(default=False),
        ),
    ]
