# Generated by Django 3.0.8 on 2020-08-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0003_auto_20200803_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='type_of_contract',
            field=models.ManyToManyField(related_name='type_of_contract', to='misclientes.Type_of_Contract'),
        ),
    ]
