# Generated by Django 2.0.6 on 2018-10-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0003_auto_20181010_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='misclientes.Enterprise'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idnum',
            field=models.IntegerField(null=True),
        ),
    ]
