# Generated by Django 2.0.6 on 2018-10-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0004_auto_20181010_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ueb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ueb_name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
