# Generated by Django 2.0.6 on 2018-10-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0005_ueb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ueb',
            field=models.ManyToManyField(to='misclientes.Ueb'),
        ),
    ]
