# Generated by Django 2.0.6 on 2018-10-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0006_cliente_ueb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contract',
            field=models.IntegerField(null=True),
        ),
    ]
