# Generated by Django 2.0.6 on 2018-10-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0007_cliente_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='enterprise',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='client',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='misclientes.Cliente'),
        ),
    ]
