# Generated by Django 2.0.6 on 2018-10-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0008_auto_20181010_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ueb',
        ),
        migrations.DeleteModel(
            name='Ueb',
        ),
    ]
