# Generated by Django 2.0.6 on 2018-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0009_auto_20181010_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='ammount_of_doubt',
            field=models.IntegerField(null=True),
        ),
    ]
