# Generated by Django 2.0.6 on 2018-10-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0010_enterprise_ammount_of_doubt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='client',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='client',
            field=models.ManyToManyField(null=True, to='misclientes.Cliente'),
        ),
    ]
