# Generated by Django 2.0.6 on 2018-10-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0011_auto_20181010_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='ammount_of_doubt',
        ),
    ]
