# Generated by Django 2.0.6 on 2018-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0013_enterprise_ammount_of_doubt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='client',
        ),
        migrations.AddField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='misclientes.Enterprise'),
        ),
    ]
