# Generated by Django 2.0.6 on 2018-10-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0014_auto_20181011_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to='misclientes.Enterprise'),
        ),
    ]
