# Generated by Django 2.0.6 on 2018-10-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0015_auto_20181011_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='clientes', to='misclientes.Enterprise'),
        ),
    ]
