# Generated by Django 2.0.6 on 2018-10-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0016_auto_20181012_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='enterprise_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
