# Generated by Django 2.0.6 on 2018-10-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0018_cliente_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
