# Generated by Django 2.0.6 on 2018-10-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0019_enterprise_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
