# Generated by Django 2.0.6 on 2018-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0020_auto_20181012_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_description',
            field=models.CharField(default='Ingrese la descripción de la empresa o algún comentario...', max_length=100, null=True),
        ),
    ]
