# Generated by Django 2.0.6 on 2019-02-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0022_auto_20190202_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='signature',
        ),
    ]
