# Generated by Django 2.0.6 on 2019-02-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0025_auto_20190217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contract',
            field=models.CharField(default='InserteNumeroDeContrato', max_length=50, verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='clientes', to='misclientes.Enterprise', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idnum',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número de Carnet'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lastname',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_name',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Empresa'),
        ),
    ]
