# Generated by Django 2.0.6 on 2019-02-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0026_auto_20190217_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(default='Comprador', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Domicilio Legal'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='bank',
            field=models.CharField(max_length=200, null=True, verbose_name='Banco en el que opera'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='bank_address',
            field=models.CharField(max_length=200, null=True, verbose_name='Direccion del Banco'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='commercial_register_cuc',
            field=models.IntegerField(max_length=6, null=True, verbose_name='Registro Comercial en CUC'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='commercial_register_cup',
            field=models.IntegerField(max_length=6, null=True, verbose_name='Registro Comercial en CUP'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='cuc_account',
            field=models.IntegerField(null=True, verbose_name='Cuenta en CUC'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='cup_account',
            field=models.IntegerField(null=True, verbose_name='Cuenta en Moneda Nacional'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='licence_to_operate_on_divisa',
            field=models.CharField(max_length=20, null=True, verbose_name='Licencia para Operar en Divisa'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nit',
            field=models.IntegerField(null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contract',
            field=models.CharField(default='InserteNumeroDeContrato', max_length=50, verbose_name='Número de Contrato'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', related_name='clientes', to='misclientes.Enterprise', verbose_name='Empresa a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idnum',
            field=models.IntegerField(null=True, verbose_name='Carnet de Identidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='lastname',
            field=models.CharField(max_length=50, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='ammount_of_doubt',
            field=models.IntegerField(null=True, verbose_name='Monto de la deuda'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='enterprise_description',
            field=models.CharField(default='Ingrese la descripción de la empresa o algún comentario...', max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='has_doubt',
            field=models.BooleanField(default=False, verbose_name='Tiene deudas?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='role',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='misclientes.Role', verbose_name='Rol que ocupa'),
        ),
    ]
