# Generated by Django 2.0.6 on 2019-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0027_auto_20190219_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='role',
        ),
    ]
