# Generated by Django 2.0.6 on 2019-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0030_auto_20190219_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='misclientes.Role'),
        ),
    ]
