# Generated by Django 2.0.6 on 2019-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0031_cliente_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contract',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='contract',
            field=models.CharField(default='InserteNumeroDeContrato', max_length=50, verbose_name='Número de Contrato'),
        ),
    ]
