# Generated by Django 2.0.6 on 2019-02-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0032_auto_20190219_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='persons',
            field=models.ManyToManyField(related_name='PersonasAutorizadas', to='misclientes.Cliente'),
        ),
    ]
