# Generated by Django 2.0.6 on 2019-02-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0033_enterprise_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enterprise',
            name='persons',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='persons',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', related_name='PersonasAutorizadas', to='misclientes.Cliente'),
        ),
    ]
