# Generated by Django 2.0.6 on 2019-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0037_enterprise_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='nit',
            field=models.PositiveIntegerField(null=True, verbose_name='NIT'),
        ),
    ]
