# Generated by Django 2.0.6 on 2019-02-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0040_auto_20190223_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='has_doubt',
            field=models.BooleanField(default=False, verbose_name='Tiene deudas?'),
        ),
    ]
