# Generated by Django 2.0.6 on 2019-02-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0041_auto_20190223_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='cuc_account',
            field=models.IntegerField(default=0, null=True, verbose_name='Cuenta en CUC'),
        ),
    ]
