# Generated by Django 2.0.6 on 2019-02-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0042_auto_20190223_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='idnum',
            field=models.IntegerField(null=True, unique=True, verbose_name='Carnet de Identidad'),
        ),
    ]
