# Generated by Django 2.0.6 on 2019-02-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0043_auto_20190224_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='cuc_account',
            field=models.IntegerField(null=True, verbose_name='Cuenta en CUC'),
        ),
    ]
