# Generated by Django 2.0.6 on 2019-02-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0044_auto_20190224_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cogido',
            field=models.BooleanField(default=True),
        ),
    ]
