# Generated by Django 2.0.6 on 2019-02-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0046_auto_20190224_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'permissions': (('view_enterprise', 'Can see available Enterprises'),)},
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='persons',
            field=models.ManyToManyField(limit_choices_to={'cogido': False}, related_name='PersonasAutorizadas', to='misclientes.Cliente'),
        ),
    ]
