# Generated by Django 2.0.6 on 2019-03-01 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0047_auto_20190228_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'permissions': (('view_enterprise', 'Hide content'),)},
        ),
    ]
