# Generated by Django 2.0.6 on 2019-03-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0048_auto_20190301_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='code',
            field=models.CharField(max_length=15, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='persons',
            field=models.ManyToManyField(limit_choices_to={'cogido': False}, related_name='personas', to='misclientes.Cliente'),
        ),
    ]
