# Generated by Django 2.0.6 on 2019-03-17 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0049_auto_20190313_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='misclientes.Enterprise'),
        ),
    ]
