# Generated by Django 2.0.6 on 2019-03-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0051_auto_20190316_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
    ]
