# Generated by Django 2.0.6 on 2019-03-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0052_remove_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='persons',
            field=models.ManyToManyField(limit_choices_to={'cogido': False}, related_name='enterprise', to='misclientes.Cliente'),
        ),
    ]
