# Generated by Django 2.0.6 on 2019-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0053_auto_20190330_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
