# Generated by Django 2.0.6 on 2019-04-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0054_enterprise_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
