# Generated by Django 2.0.6 on 2019-04-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0055_cliente_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
    ]
