# Generated by Django 2.0.6 on 2019-04-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0056_enterprise_emailed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['idnum']},
        ),
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['last_update'], 'permissions': (('view_enterprise', 'Hide content'),), 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='enterprise',
            name='persons',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='persons',
            field=models.ForeignKey(limit_choices_to={'cogido': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise', to='misclientes.Cliente'),
        ),
    ]
