# Generated by Django 2.0.6 on 2019-04-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0058_auto_20190411_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente',
            field=models.ManyToManyField(limit_choices_to={'cogido': False}, related_name='enterprise', to='misclientes.Enterprise'),
        ),
    ]
