# Generated by Django 2.0.6 on 2019-04-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0059_auto_20190411_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='persons',
            field=models.ManyToManyField(limit_choices_to={'cogido': False}, related_name='enterprise', to='misclientes.Cliente'),
        ),
    ]
