# Generated by Django 2.0.6 on 2019-04-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0061_auto_20190419_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='commercial_register_cuc',
            field=models.IntegerField(null=True, verbose_name='Registro Comercial en CUC'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='commercial_register_cup',
            field=models.IntegerField(null=True, verbose_name='Registro Comercial en CUP'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cuc_account',
            field=models.IntegerField(null=True, verbose_name='Cuenta en CUC'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='cup_account',
            field=models.IntegerField(null=True, verbose_name='Cuenta en Moneda Nacional'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='email',
            field=models.EmailField(default='email@empresa.cu', max_length=254),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='licence_to_operate_on_divisa',
            field=models.CharField(max_length=20, null=True, verbose_name='Licencia para Operar en Divisa'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Número de Teléfono'),
        ),
    ]
