# Generated by Django 2.0.6 on 2019-04-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0062_auto_20190419_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['last_update'], 'permissions': (('view_enterprise', 'Hide content'), ('can_deliver_pizza', 'Puede repartir pizza')), 'verbose_name_plural': 'Empresas'},
        ),
    ]
