# Generated by Django 2.0.6 on 2019-04-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0063_auto_20190419_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['last_update'], 'permissions': (('cambiar_enterprise', 'Puede Editar Empresas'),), 'verbose_name_plural': 'Empresas'},
        ),
    ]
