# Generated by Django 2.0.6 on 2019-05-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0068_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='updated',
            field=models.BooleanField(default=False, verbose_name='Actualizado?'),
        ),
    ]
