# Generated by Django 2.0.6 on 2019-07-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0070_auto_20190702_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='ammount_of_doubt',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
