# Generated by Django 2.0.6 on 2019-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misclientes', '0071_auto_20190711_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='ammount_of_doubt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
