# Generated by Django 2.0.6 on 2019-04-21 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_ordering_by', models.CharField(choices=[('code', 'Codigo REUP'), ('last_update', 'Fecha de actualizacion'), ('enterprise_name', 'Nombre del Cliente'), ('nit', 'NIT')], default='last_update', max_length=30)),
                ('persons_ordering_by', models.CharField(choices=[('lastname', 'Apellidos'), ('idnum', 'Carnet de Identidad'), ('name', 'Nombre')], default='idnum', max_length=50)),
                ('app_color_theme', models.CharField(choices=[('blue', 'Azul'), ('black', 'Negro'), ('green', 'Verde'), ('purple', 'Violeta'), ('red', 'Rojo'), ('yellow', 'Amarillo')], default='indigo', max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
